// User
export const FETCH_USER_LOADING = 'FETCH_USER_LOADING';
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'; // ?
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';
export const SET_USER_AVATAR = 'SET_USER_AVATAR';
export const SET_USER_AVATAR_FAILURE = 'SET_USER_AVATAR_FAILURE';

// Settings
export const CHANGE_COLOR_THEME = 'CHANGE_COLOR_THEME';
export const CHANGE_DESIGN_THEME = 'CHANGE_DESIGN_THEME';
export const CHANGE_WINTER_DESIGN_SNOWFLARE_COUNT =
  'CHANGE_WINTER_DESIGN_SNOWFLARE_COUNT';
export const CHANGE_WINTER_DESIGN_SNOWFLARE_SPEED =
  'CHANGE_WINTER_DESIGN_SNOWFLARE_SPEED';
export const CHANGE_WINTER_DESIGN_SNOWFLARE_WIND =
  'CHANGE_WINTER_DESIGN_SNOWFLARE_WIND';
export const CHANGE_WINTER_DESIGN_SNOWFLARE_RADIUS =
  'CHANGE_WINTER_DESIGN_SNOWFLARE_RADIUS';
export const CHANGE_WINTER_DESIGN_SNOWFLARE_COLOR =
  'CHANGE_WINTER_DESIGN_SNOWFLARE_COLOR';
export const RESET_WINTER_DESIGN_CHANGES = 'RESET_WINTER_DESIGN_CHANGES';
export const CHANGE_WINTER_DESIGN_SHOW_CHRISTMAS_LIGHTS =
  'CHANGE_WINTER_DESIGN_SHOW_CHRISTMAS_LIGHTS';

// Search
export const SEARCH_LOADING = 'SEARCH_LOADING';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
export const FETCH_SEARCH_FAILURE = 'FETCH_SEARCH_FAILURE';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';

// Group
export const FETCH_GROUP_LOADING = 'FETCH_GROUP_LOADING';
export const FETCH_GROUP_SUCCESS = 'FETCH_GROUP_SUCCESS';
export const FETCH_GROUP_FAILURE = 'FETCH_GROUP_FAILURE';
export const JOIN_GROUP_SUCCESS = 'JOIN_GROUP_SUCCESS';
export const UNJOIN_GROUP_SUCCESS = 'UNJOIN_GROUP_SUCCESS';
export const CHECK_IS_GROUP_MEMBER_SUCCESS = 'CHECK_IS_GROUP_MEMBER_SUCCESS';
export const SET_GROUP_VERIFICATION = 'SET_GROUP_VERIFICATION';

// Post
export const FETCH_POST_FAILURE = 'FETCH_POST_FAILURE';
export const FETCH_POST_LOADING = 'FETCH_POST_LOADING';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_USER_SUCCESS = 'FETCH_POST_USER_SUCCESS';
export const RATE_POST_SUCCESS = 'RATE_POST_SUCCESS';

// Complaint
export const COMPLAINT_OPEN_POPUP = 'COMPLAINT_OPEN_POPUP';
export const COMPLAINT_CLOSE_POPUP = 'COMPLAINT_CLOSE_POPUP';
export const COMPLAINT_SET_REASON = 'COMPLAINT_SET_REASON';
export const COMPLAINT_SUBMIT_ERROR = 'COMPLAINT_SUBMIT_ERROR';
export const COMPLAINT_SUBMIT_LOADING = 'COMPLAINT_SUBMIT_LOADING';
export const COMPLAINT_SUBMIT_SUCCESS = 'COMPLAINT_SUBMIT_SUCCESS';

// Global chat
export const GLOBAL_CHAT_SET_MESSAGE = 'GLOBAL_CHAT_SET_MESSAGE';
export const GLOBAL_CHAT_SET_REPLY_TO_MESSAGE_ID =
  'GLOBAL_CHAT_SET_REPLY_TO_MESSAGE_ID';
export const GLOBAL_CHAT_CANCEL_REPLY_TO = 'GLOBAL_CHAT_CANCEL_REPLY_TO';
export const GLOBAL_CHAT_SET_MESSAGES_LIST = 'GLOBAL_CHAT_SET_MESSAGES_LIST';
export const GLOBAL_CHAT_ADD_MESSAGE = 'GLOBAL_CHAT_ADD_MESSAGE';
export const GLOBAL_CHAT_NEW_MESSAGE_WAS_SENT =
  'GLOBAL_CHAT_NEW_MESSAGE_WAS_SENT';

// Personal
export const PERSONAL_SET_UNREAD_CHATS = 'PERSONAL_SET_UNREAD_CHATS';
export const PERSONAL_SET_CURRENT_CHAT_INTERLOCUTOR_ID =
  'PERSONAL_SET_CURRENT_CHAT_INTERLOCUTOR_ID';
